---
# Configuration options for Scrutinizer CI

checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_code_sniffer:
        config:
            standard: "PSR2"
    php_cs_fixer:
      enabled: true
      config: { level: psr2 }

